### ISSUE TITLE
Comment clipped

### ISSUE THREAD

**Issue by vk2io** [RhinoLance/ParksNPeaks_Heimdall#3]
When using the respot function the comment that was posted to ParksnPeaks only contained the first word of the sentence entered in the comment box.

Also, when attempting to enter a comment, a droplist of earlier comments appears. If one attempts to select an earlier comment by moving the mouse over them the whole respot operation is aborted.

**Comment by RhinoLance** [comment]
Thanks for raising these issues Gerard.  I have moved the hiding panel issue to track it separately in https://github.com/RhinoLance/ParksNPeaks_Heimdall/issues/4

**Comment by RhinoLance** [comment]
Hmmm, it worked fine in testing, and posted a re-spot today and all was well.  I wonder if it was an artifact of the resetting input as noted, which has been resolved.

Gerard, I would appreciate you trying again and letting me know if the problem persists.  Whilst it should make no difference, please provide the spot text it clips it again.

**Comment by vk2io** [comment]
Thanks Lance.
On v1.01 I tried respotting and it works fine now.
The whole comment was sent thru to ParksnPeaks.
73, Gerard

**Comment by RhinoLance** [comment]
Excellent!  Thanks for the test.
